version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  admin-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: adminpass
      MYSQL_DATABASE: admindb
    ports:
      - "3306:3306"

  frontend-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: frontendpass
      MYSQL_DATABASE: frontenddb
    ports:
      - "3307:3306"

  admin-api:
    build: ./admin_api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_HOST: admin-db
    ports:
      - "8000:8000"
    depends_on:
      - admin-db
      - kafka

  frontend-api:
    build: ./frontend_api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    environment:
      DB_HOST: frontend-db
    ports:
      - "8001:8001"
    depends_on:
      - frontend-db
      - kafka